name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        description: Name of the artifact to download
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploying & uploading ..."
