name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        description: Name of the artifact to download
        required: true
        default: dist
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome}}
    # secrets:
    #   some_secret:
    #     required: true
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set_result.outputs.set_result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploying & uploading ..."
      - name: Set result output
        id: set_result
        run: echo "::set-output name=set-result::success"
